stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./icinga2/Dockerfile
      buildContext: ./icinga2/
      tag: labtagon/icinga2:latest
      pushRemote: true
      registry: registry.labtagon.com
timeout: 60
notification: {}
