stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./icinga2/
      tag: labtagon/icinga2:latest
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
